library(readxl)
library(corrplot)
#read_data
data3=read_excel("C:\\Users\\tuanvl\\Desktop\\ThS\\Ex6\\data3.xls")
str(data3)
#base_model
mod0=lm(FUEL~1,data=data3)
mod1=lm(FUEL~.,data=data3)
#1.Stepwise_backward
bestmod=step(mod1)
summary(bestmod)
#2.Stagewise
#step1
corrplot(cor(data3),method="number")
md1=lm(FUEL~DLIC,data=data3)
res1=residuals(md1)
#step2
data3$res1=res1
corrplot(cor(data3[c("TAX","INC","ROAD","res1")]),method="number")
md2=lm(res1~INC,data=data3)
res2=residuals(md2)         
#step2
data3$res2=res2
corrplot(cor(data3[c("TAX","ROAD","res2")]),method="number")
md3=lm(res2~TAX,data=data3)
res3=residuals(md3)
#step3
cor(data3$ROAD,res3)
bestmod_stage=lm(FUEL~DLIC+INC+TAX,data=data3)
summary(bestmod_stage)
